#!/usr/bin/env bash
# verify.sh — every gate this repo has, in one command.
#
# GENERATED by claude-code-policy/bin/gate-enrol.py. Edit it freely: it is this
# repo's file now, and the enroller never overwrites one that already exists.
#
# `.githooks/pre-push` runs this before anything leaves the machine, through
# `claude-gate-run` when the offload rail is configured — so the suite runs on the
# shared runner and this file is what the runner is asked to execute.
#
# IT PROVISIONS FIRST, DELIBERATELY. A bare `pytest` submitted to the runner fails
# with ModuleNotFoundError because nothing installed this repo's dependencies there;
# a command that asks for an environment gets one, built from the repo's own tracked
# declaration. That is the measured difference between a row on the gate-fallback
# board and a green gate.
set -uo pipefail
cd "$(dirname "$0")" || exit 1
rc=0

echo "== tests/run.sh =="
if command -v claude-gate-run >/dev/null 2>&1; then
  claude-gate-run --two-rail -- bash tests/run.sh || rc=1
else
  bash tests/run.sh || rc=1
fi

echo
if [ "$rc" -eq 0 ]; then
  echo "ALL GATES PASSED"
else
  echo "GATES FAILED — do not push"
fi
exit "$rc"
